name: Criar Executavel Organizador
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Build EXE
        # AQUI: Se o seu arquivo de organizar tiver outro nome no GitHub, mude 'organizar.py' abaixo
        run: pyinstaller --onefile --console --name "Organizador_Rapha" organizar_pastas.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Organizador-Windows
          path: dist/Organizador_Rapha.exe
